# MarsPro Integration Services

set_spectrum:
  name: Set Light Spectrum
  description: Set the light spectrum for MarsPro grow lights
  target:
    entity:
      domain: light
  fields:
    red:
      name: Red
      description: Red component (0-255)
      example: 255
      selector:
        number:
          min: 0
          max: 255
    green:
      name: Green
      description: Green component (0-255)
      example: 200
      selector:
        number:
          min: 0
          max: 255
    blue:
      name: Blue
      description: Blue component (0-255)
      example: 150
      selector:
        number:
          min: 0
          max: 255
    white:
      name: White
      description: White component (0-255)
      example: 100
      selector:
        number:
          min: 0
          max: 255

set_schedule:
  name: Set Schedule
  description: Set the schedule for MarsPro devices
  target:
    entity:
      integration: marspro
  fields:
    schedule:
      name: Schedule
      description: Schedule configuration as JSON
      example: '{"enabled": true, "times": [{"start": "06:00", "brightness": 80}]}'
      selector:
        object:

calibrate_sensors:
  name: Calibrate Sensors
  description: Calibrate environmental sensors
  target:
    entity:
      domain: sensor
      integration: marspro
  fields: {}

reset_device:
  name: Reset Device
  description: Reset a MarsPro device to factory settings
  target:
    entity:
      integration: marspro
  fields: {}
